version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    network_mode: host
    container_name: opa-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-opa_policies}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:4.23
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  bundle-server:
    build:
      context: ./bundle-server
    container_name: opa-bundle-server
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${BUNDLE_SERVER_PORT:-8080}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin:

